// GENERATED by scripts/gen-api-types.mjs — do not edit by hand.
// Regenerate with: npm run gen:api
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description Liveness + version handshake for the frontend.
     */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/remotes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Remotes */
    get: operations["list_remotes_api_remotes_get"];
    put?: never;
    /** Add Remote */
    post: operations["add_remote_api_remotes_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/remotes/{name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update Remote */
    put: operations["update_remote_api_remotes__name__put"];
    post?: never;
    /** Remove Remote */
    delete: operations["remove_remote_api_remotes__name__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/remotes/{name}/connect": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Connect Remote */
    post: operations["connect_remote_api_remotes__name__connect_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/remotes/{name}/disconnect": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Disconnect Remote */
    post: operations["disconnect_remote_api_remotes__name__disconnect_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/remotes/{name}/benchmarks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Remote Benchmarks
     * @description `crab list-benchmarks --json` on the connected cluster (for the wrapper picker).
     *
     *     Introspection runs every wrapper module on the login node, so allow a generous
     *     timeout; the contract degrades unloadable wrappers gracefully rather than failing.
     */
    get: operations["remote_benchmarks_api_remotes__name__benchmarks_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/remotes/{name}/nodes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Remote Nodes
     * @description `crab nodes --json` on the connected cluster (informational partition list).
     */
    get: operations["remote_nodes_api_remotes__name__nodes_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/remotes/{name}/bootstrap/plan": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Bootstrap Plan */
    post: operations["bootstrap_plan_api_remotes__name__bootstrap_plan_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/remotes/{name}/bootstrap/install": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Bootstrap Install */
    post: operations["bootstrap_install_api_remotes__name__bootstrap_install_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/remotes/{name}/bootstrap/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Bootstrap Verify */
    post: operations["bootstrap_verify_api_remotes__name__bootstrap_verify_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/experiments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Experiments */
    get: operations["list_experiments_api_experiments_get"];
    put?: never;
    /** Create Experiment */
    post: operations["create_experiment_api_experiments_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/experiments/{entry_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Experiment */
    get: operations["get_experiment_api_experiments__entry_id__get"];
    /** Update Experiment */
    put: operations["update_experiment_api_experiments__entry_id__put"];
    post?: never;
    /** Delete Experiment */
    delete: operations["delete_experiment_api_experiments__entry_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/experiments/{entry_id}/duplicate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Duplicate Experiment */
    post: operations["duplicate_experiment_api_experiments__entry_id__duplicate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/local/benchmarks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Local Benchmarks
     * @description `crab list-benchmarks --json` on the machine running crab web.
     *
     *     Introspection runs every wrapper module, so allow the same generous
     *     timeout as the remote path.
     */
    get: operations["local_benchmarks_api_local_benchmarks_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * BootstrapStep
     * @description One install command, shown to the user as a readable preview.
     */
    BootstrapStep: {
      /** Id */
      id: string;
      /** Label */
      label: string;
      /** Command */
      command: string;
    };
    /** ConfigBody */
    ConfigBody: {
      /**
       * Name
       * @default
       */
      name: string;
      /** Config */
      config?: {
        [key: string]: unknown;
      };
    };
    /** ConnectRequest */
    ConnectRequest: {
      /** Password */
      password?: string | null;
    };
    /** DetectResult */
    DetectResult: {
      /** Installed */
      installed: boolean;
      /** Info */
      info?: {
        [key: string]: unknown;
      } | null;
      /** Reason */
      reason?: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** InstallRequest */
    InstallRequest: {
      /** Pre Commands */
      pre_commands?: string[];
    };
    /** LibraryEntry */
    LibraryEntry: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Updated At */
      updated_at: string;
      /** Config */
      config: {
        [key: string]: unknown;
      };
    };
    /** PlanResponse */
    PlanResponse: {
      /** Installed */
      installed: boolean;
      /** Info */
      info?: {
        [key: string]: unknown;
      } | null;
      /** Reason */
      reason?: string | null;
      /** Pre Commands */
      pre_commands: string[];
      /** Steps */
      steps: components["schemas"]["BootstrapStep"][];
    };
    /**
     * Profile
     * @description A cluster the dashboard can connect to.
     */
    Profile: {
      /**
       * Name
       * @description Unique local alias for this cluster.
       */
      name: string;
      /**
       * Transport
       * @default ssh
       * @enum {string}
       */
      transport: "ssh" | "local";
      /** Host */
      host?: string | null;
      /**
       * Port
       * @default 22
       */
      port: number;
      /** User */
      user?: string | null;
      /**
       * Auth
       * @default agent
       * @enum {string}
       */
      auth: "agent" | "key" | "password";
      /** Key Path */
      key_path?: string | null;
      /**
       * Hostkey Policy
       * @default strict
       * @enum {string}
       */
      hostkey_policy: "strict" | "insecure";
      /**
       * Remote Crab
       * @default ~
       */
      remote_crab: string;
      /**
       * Venv Activate
       * @description Path to the venv activate script; defaults to <remote_crab>/CRAB/.venv/bin/activate.
       */
      venv_activate?: string | null;
      /**
       * Remote Setup
       * @description Commands run before activation (e.g. 'module load python').
       */
      remote_setup?: string[];
      /** Preset */
      preset?: string | null;
    };
    /**
     * RemoteListItem
     * @description A profile annotated with its live connection state.
     */
    RemoteListItem: {
      /**
       * Name
       * @description Unique local alias for this cluster.
       */
      name: string;
      /**
       * Transport
       * @default ssh
       * @enum {string}
       */
      transport: "ssh" | "local";
      /** Host */
      host?: string | null;
      /**
       * Port
       * @default 22
       */
      port: number;
      /** User */
      user?: string | null;
      /**
       * Auth
       * @default agent
       * @enum {string}
       */
      auth: "agent" | "key" | "password";
      /** Key Path */
      key_path?: string | null;
      /**
       * Hostkey Policy
       * @default strict
       * @enum {string}
       */
      hostkey_policy: "strict" | "insecure";
      /**
       * Remote Crab
       * @default ~
       */
      remote_crab: string;
      /**
       * Venv Activate
       * @description Path to the venv activate script; defaults to <remote_crab>/CRAB/.venv/bin/activate.
       */
      venv_activate?: string | null;
      /**
       * Remote Setup
       * @description Commands run before activation (e.g. 'module load python').
       */
      remote_setup?: string[];
      /** Preset */
      preset?: string | null;
      /**
       * Connected
       * @default false
       */
      connected: boolean;
    };
    /**
     * SavedEntry
     * @description A stored entry plus any shape warnings for the config just saved.
     */
    SavedEntry: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Updated At */
      updated_at: string;
      /** Config */
      config: {
        [key: string]: unknown;
      };
      /**
       * Warnings
       * @default []
       */
      warnings: string[];
    };
    /** StepResult */
    StepResult: {
      /** Rc */
      rc: number;
      /** Ok */
      ok: boolean;
      /** Stdout */
      stdout: string;
      /** Stderr */
      stderr: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  list_remotes_api_remotes_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RemoteListItem"][];
        };
      };
    };
  };
  add_remote_api_remotes_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Profile"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Profile"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_remote_api_remotes__name__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Profile"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Profile"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  remove_remote_api_remotes__name__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  connect_remote_api_remotes__name__connect_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ConnectRequest"] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  disconnect_remote_api_remotes__name__disconnect_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  remote_benchmarks_api_remotes__name__benchmarks_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  remote_nodes_api_remotes__name__nodes_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  bootstrap_plan_api_remotes__name__bootstrap_plan_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlanResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  bootstrap_install_api_remotes__name__bootstrap_install_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InstallRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StepResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  bootstrap_verify_api_remotes__name__bootstrap_verify_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DetectResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_experiments_api_experiments_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LibraryEntry"][];
        };
      };
    };
  };
  create_experiment_api_experiments_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConfigBody"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SavedEntry"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_experiment_api_experiments__entry_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        entry_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LibraryEntry"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_experiment_api_experiments__entry_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        entry_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConfigBody"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SavedEntry"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_experiment_api_experiments__entry_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        entry_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  duplicate_experiment_api_experiments__entry_id__duplicate_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        entry_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LibraryEntry"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  local_benchmarks_api_local_benchmarks_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
}
