// GENERATED by scripts/gen-api-types.mjs — do not edit by hand.
// Regenerate with: npm run gen:api
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description Liveness + version handshake for the frontend.
     */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/remotes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Remotes */
    get: operations["list_remotes_api_remotes_get"];
    put?: never;
    /** Add Remote */
    post: operations["add_remote_api_remotes_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/remotes/{name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update Remote */
    put: operations["update_remote_api_remotes__name__put"];
    post?: never;
    /** Remove Remote */
    delete: operations["remove_remote_api_remotes__name__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/remotes/{name}/connect": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Connect Remote */
    post: operations["connect_remote_api_remotes__name__connect_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/remotes/{name}/disconnect": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Disconnect Remote */
    post: operations["disconnect_remote_api_remotes__name__disconnect_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/remotes/{name}/benchmarks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Remote Benchmarks
     * @description `crab list-benchmarks --json` on the connected cluster (for the wrapper picker).
     *
     *     Introspection runs every wrapper module on the login node, so allow a generous
     *     timeout; the contract degrades unloadable wrappers gracefully rather than failing.
     */
    get: operations["remote_benchmarks_api_remotes__name__benchmarks_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/remotes/{name}/nodes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Remote Nodes
     * @description `crab nodes --json` on the connected cluster (informational partition list).
     */
    get: operations["remote_nodes_api_remotes__name__nodes_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/remotes/{name}/bootstrap/plan": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Bootstrap Plan */
    post: operations["bootstrap_plan_api_remotes__name__bootstrap_plan_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/remotes/{name}/bootstrap/install": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Bootstrap Install */
    post: operations["bootstrap_install_api_remotes__name__bootstrap_install_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/remotes/{name}/bootstrap/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Bootstrap Verify */
    post: operations["bootstrap_verify_api_remotes__name__bootstrap_verify_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/experiments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Experiments */
    get: operations["list_experiments_api_experiments_get"];
    put?: never;
    /** Create Experiment */
    post: operations["create_experiment_api_experiments_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/experiments/{entry_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Experiment */
    get: operations["get_experiment_api_experiments__entry_id__get"];
    /** Update Experiment */
    put: operations["update_experiment_api_experiments__entry_id__put"];
    post?: never;
    /** Delete Experiment */
    delete: operations["delete_experiment_api_experiments__entry_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/experiments/{entry_id}/duplicate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Duplicate Experiment */
    post: operations["duplicate_experiment_api_experiments__entry_id__duplicate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/local/benchmarks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Local Benchmarks
     * @description `crab list-benchmarks --json` on the machine running crab web.
     *
     *     Introspection runs every wrapper module, so allow the same generous
     *     timeout as the remote path.
     */
    get: operations["local_benchmarks_api_local_benchmarks_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs/submit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Submit Job
     * @description Validate synchronously, then stage/run in the background (plan 075).
     *
     *     Everything that can fail instantly (profile exists, connected, config
     *     resolves, a preset is chosen) still happens before responding, same as
     *     before — only the SSH round-trip (staging + `crab run`) moves off the
     *     request cycle, since that's what used to make a submit or rerun feel like
     *     it hung with no feedback.
     */
    post: operations["submit_job_api_jobs_submit_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs/submissions/{submission_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Submission
     * @description Poll a submission's status; 404 once a terminal result has been fetched.
     *
     *     Entries are dropped from the tracker as soon as a terminal status is
     *     returned so it doesn't grow forever (there's no other cleanup — the
     *     tracker is in-memory and process-lifetime only).
     */
    get: operations["get_submission_api_jobs_submissions__submission_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Jobs
     * @description Registry ⨝ live `crab status`, batched one call per cluster with active jobs.
     *
     *     A disconnected cluster's jobs are returned as-is (last known state,
     *     `connected: false`) rather than failing the whole list.
     */
    get: operations["list_jobs_api_jobs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs/{record_id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cancel Job */
    post: operations["cancel_job_api_jobs__record_id__cancel_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs/{record_id}/logs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Job Logs
     * @description Job-level slurm logs, or one experiment's per-app error logs if `experiment` is given.
     *
     *     Live-first with a local-cache fallback (plan 075): a disconnected cluster or
     *     a failed remote command falls back to the last successfully fetched copy
     *     for this exact key, marked `stale`, instead of blanking the logs panel.
     *     A key miss (never fetched before) still raises exactly as before.
     */
    get: operations["job_logs_api_jobs__record_id__logs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs/{record_id}/experiments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Job Experiments
     * @description Every `crab history` row for this exact submission, not the whole use case.
     *
     *     Same worst-first-independent matching as `_resolve_via_history`/`use_case_report`
     *     (a data_dir's basename against a history row's `relative_path` prefix), but
     *     returns every matching row instead of collapsing to one worst status.
     */
    get: operations["job_experiments_api_jobs__record_id__experiments_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs/report/{config_name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Use Case Report
     * @description Every experiment ever run under `config_name`, across every connected cluster.
     *
     *     Sourced from `crab history --json` (authoritative — matches manual runs too,
     *     not only ones submitted through this dashboard), then joined against the
     *     local job registry just for submit metadata (job id, submitted_at). A
     *     disconnected cluster is skipped and named in `clusters_skipped` rather than
     *     silently omitted, same convention as `list_jobs`'s `connected` flag. A
     *     disconnected cluster with a prior cached fetch falls back to it instead of
     *     being skipped, named in `clusters_stale` (plan 075) rather than
     *     `clusters_skipped` — the caller can still tell the two cases apart.
     */
    get: operations["use_case_report_api_jobs_report__config_name__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs/{record_id}/results/fetch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Fetch Results
     * @description Validate synchronously (job exists, cluster connected), then fetch in the background.
     */
    post: operations["fetch_results_api_jobs__record_id__results_fetch_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs/{record_id}/results/fetch/{fetch_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Fetch Status
     * @description Poll a fetch's status; 404 once a terminal result has been fetched.
     *
     *     Entries are dropped from the tracker as soon as a terminal status is
     *     returned so it doesn't grow forever (there's no other cleanup — the
     *     tracker is in-memory and process-lifetime only, same as jobs.py's).
     */
    get: operations["get_fetch_status_api_jobs__record_id__results_fetch__fetch_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs/{record_id}/results": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Results
     * @description The cached CSV tree for this job, parsed. 404 if it was never fetched.
     */
    get: operations["get_results_api_jobs__record_id__results_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs/results/cache": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Results Cache Size */
    get: operations["get_results_cache_size_api_jobs_results_cache_get"];
    put?: never;
    post?: never;
    /** Clear Results Cache */
    delete: operations["clear_results_cache_api_jobs_results_cache_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * BootstrapStep
     * @description One install command, shown to the user as a readable preview.
     */
    BootstrapStep: {
      /** Id */
      id: string;
      /** Label */
      label: string;
      /** Command */
      command: string;
    };
    /** CacheSize */
    CacheSize: {
      /** Total Bytes */
      total_bytes: number;
    };
    /** CancelResponse */
    CancelResponse: {
      job: components["schemas"]["JobRecord"];
      /** Cancelled */
      cancelled: boolean;
      /** Detail */
      detail?: string | null;
    };
    /** ConfigBody */
    ConfigBody: {
      /**
       * Name
       * @default
       */
      name: string;
      /** Config */
      config?: {
        [key: string]: unknown;
      };
    };
    /** ConnectRequest */
    ConnectRequest: {
      /** Password */
      password?: string | null;
    };
    /** DetectResult */
    DetectResult: {
      /** Installed */
      installed: boolean;
      /** Info */
      info?: {
        [key: string]: unknown;
      } | null;
      /** Reason */
      reason?: string | null;
    };
    /** FetchAccepted */
    FetchAccepted: {
      /** Fetch Id */
      fetch_id: string;
    };
    /**
     * FetchStatus
     * @description Polled result of an async results fetch. `status` is one of
     *     "pending", "done", "error".
     */
    FetchStatus: {
      /** Status */
      status: string;
      /** Message */
      message?: string | null;
      /** Detail */
      detail?: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** InstallRequest */
    InstallRequest: {
      /** Pre Commands */
      pre_commands?: string[];
    };
    /**
     * JobDetail
     * @description Every `crab history` row for one exact submission (plan 075's detail view).
     */
    JobDetail: {
      /** Record Id */
      record_id: string;
      /** Config Name */
      config_name: string;
      /** Cluster */
      cluster: string;
      /** System */
      system: string;
      /** Job Id */
      job_id: string;
      /** Submitted At */
      submitted_at: string;
      /** Experiments */
      experiments: components["schemas"]["ReportExperiment"][];
      /** Stale */
      stale: boolean;
      /** Cached At */
      cached_at?: string | null;
      rerun_of?: components["schemas"]["JobRecord"] | null;
      /** Rerun Experiments */
      rerun_experiments?: string[] | null;
      /** Reruns */
      reruns: components["schemas"]["JobRecord"][];
    };
    /**
     * JobListItem
     * @description A job record annotated with whether its cluster is currently connected.
     */
    JobListItem: {
      /** Id */
      id: string;
      /** Cluster */
      cluster: string;
      /** Job Id */
      job_id: string;
      /** Data Dir */
      data_dir: string;
      /** System */
      system: string;
      /** Config Name */
      config_name: string;
      /** Config Snapshot */
      config_snapshot: {
        [key: string]: unknown;
      };
      /** Submitted At */
      submitted_at: string;
      /**
       * Last Known State
       * @default UNKNOWN
       */
      last_known_state: string;
      /** Rerun Of */
      rerun_of?: string | null;
      /** Rerun Experiments */
      rerun_experiments?: string[] | null;
      /**
       * Connected
       * @default false
       */
      connected: boolean;
    };
    /** JobRecord */
    JobRecord: {
      /** Id */
      id: string;
      /** Cluster */
      cluster: string;
      /** Job Id */
      job_id: string;
      /** Data Dir */
      data_dir: string;
      /** System */
      system: string;
      /** Config Name */
      config_name: string;
      /** Config Snapshot */
      config_snapshot: {
        [key: string]: unknown;
      };
      /** Submitted At */
      submitted_at: string;
      /**
       * Last Known State
       * @default UNKNOWN
       */
      last_known_state: string;
      /** Rerun Of */
      rerun_of?: string | null;
      /** Rerun Experiments */
      rerun_experiments?: string[] | null;
    };
    /** LibraryEntry */
    LibraryEntry: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Updated At */
      updated_at: string;
      /** Config */
      config: {
        [key: string]: unknown;
      };
    };
    /** PlanResponse */
    PlanResponse: {
      /** Installed */
      installed: boolean;
      /** Info */
      info?: {
        [key: string]: unknown;
      } | null;
      /** Reason */
      reason?: string | null;
      /** Pre Commands */
      pre_commands: string[];
      /** Steps */
      steps: components["schemas"]["BootstrapStep"][];
    };
    /**
     * Profile
     * @description A cluster the dashboard can connect to.
     */
    Profile: {
      /**
       * Name
       * @description Unique local alias for this cluster.
       */
      name: string;
      /**
       * Transport
       * @default ssh
       * @enum {string}
       */
      transport: "ssh" | "local";
      /** Host */
      host?: string | null;
      /**
       * Port
       * @default 22
       */
      port: number;
      /** User */
      user?: string | null;
      /**
       * Auth
       * @default agent
       * @enum {string}
       */
      auth: "agent" | "key" | "password";
      /** Key Path */
      key_path?: string | null;
      /**
       * Hostkey Policy
       * @default strict
       * @enum {string}
       */
      hostkey_policy: "strict" | "insecure";
      /**
       * Remote Crab
       * @default ~
       */
      remote_crab: string;
      /**
       * Venv Activate
       * @description Path to the venv activate script; defaults to <remote_crab>/CRAB/.venv/bin/activate.
       */
      venv_activate?: string | null;
      /**
       * Remote Setup
       * @description Commands run before activation (e.g. 'module load python').
       */
      remote_setup?: string[];
      /** Preset */
      preset?: string | null;
    };
    /**
     * RemoteListItem
     * @description A profile annotated with its live connection state.
     */
    RemoteListItem: {
      /**
       * Name
       * @description Unique local alias for this cluster.
       */
      name: string;
      /**
       * Transport
       * @default ssh
       * @enum {string}
       */
      transport: "ssh" | "local";
      /** Host */
      host?: string | null;
      /**
       * Port
       * @default 22
       */
      port: number;
      /** User */
      user?: string | null;
      /**
       * Auth
       * @default agent
       * @enum {string}
       */
      auth: "agent" | "key" | "password";
      /** Key Path */
      key_path?: string | null;
      /**
       * Hostkey Policy
       * @default strict
       * @enum {string}
       */
      hostkey_policy: "strict" | "insecure";
      /**
       * Remote Crab
       * @default ~
       */
      remote_crab: string;
      /**
       * Venv Activate
       * @description Path to the venv activate script; defaults to <remote_crab>/CRAB/.venv/bin/activate.
       */
      venv_activate?: string | null;
      /**
       * Remote Setup
       * @description Commands run before activation (e.g. 'module load python').
       */
      remote_setup?: string[];
      /** Preset */
      preset?: string | null;
      /**
       * Connected
       * @default false
       */
      connected: boolean;
    };
    /**
     * ReportExperiment
     * @description One `crab history` row for a use case, joined with local submit metadata if known.
     */
    ReportExperiment: {
      /** Cluster */
      cluster: string;
      /** System */
      system: string;
      /** Job Name */
      job_name: string;
      /** Experiment Name */
      experiment_name: string;
      /** Timestamp */
      timestamp: string;
      /** Numnodes */
      numnodes: string;
      /** Ppn */
      ppn: string;
      /** Apps List */
      apps_list: string;
      /** Status */
      status: string;
      /** Tags */
      tags: string;
      /** Relative Path */
      relative_path: string;
      /** Record Id */
      record_id?: string | null;
      /** Job Id */
      job_id?: string | null;
      /** Submitted At */
      submitted_at?: string | null;
    };
    /** ResultsData */
    ResultsData: {
      /** Labs */
      labs: {
        [key: string]: {
          [key: string]: {
            [key: string]: unknown;
          }[];
        };
      };
    };
    /**
     * SavedEntry
     * @description A stored entry plus any shape warnings for the config just saved.
     */
    SavedEntry: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Updated At */
      updated_at: string;
      /** Config */
      config: {
        [key: string]: unknown;
      };
      /**
       * Warnings
       * @default []
       */
      warnings: string[];
    };
    /**
     * StaleCluster
     * @description One cluster whose history in this report came from the local cache, not live.
     */
    StaleCluster: {
      /** Cluster */
      cluster: string;
      /** Cached At */
      cached_at: string;
    };
    /** StepResult */
    StepResult: {
      /** Rc */
      rc: number;
      /** Ok */
      ok: boolean;
      /** Stdout */
      stdout: string;
      /** Stderr */
      stderr: string;
    };
    /** SubmissionAccepted */
    SubmissionAccepted: {
      /** Submission Id */
      submission_id: string;
    };
    /**
     * SubmissionStatus
     * @description Polled result of an async submit/rerun (plan 075). `status` is one of
     *     "pending", "done", "error".
     */
    SubmissionStatus: {
      /** Status */
      status: string;
      record?: components["schemas"]["JobRecord"] | null;
      /** Message */
      message?: string | null;
      /** Detail */
      detail?: string | null;
    };
    /** SubmitRequest */
    SubmitRequest: {
      /** Profile Name */
      profile_name: string;
      /** Config Id */
      config_id?: string | null;
      /** Config */
      config?: {
        [key: string]: unknown;
      } | null;
      /** Name */
      name?: string | null;
      /** Preset */
      preset?: string | null;
      /** Only */
      only?: string[] | null;
      /** Rerun Of */
      rerun_of?: string | null;
    };
    /** UseCaseReport */
    UseCaseReport: {
      /** Config Name */
      config_name: string;
      /** Experiments */
      experiments: components["schemas"]["ReportExperiment"][];
      /** Clusters Skipped */
      clusters_skipped: string[];
      /** Clusters Stale */
      clusters_stale: components["schemas"]["StaleCluster"][];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  list_remotes_api_remotes_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RemoteListItem"][];
        };
      };
    };
  };
  add_remote_api_remotes_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Profile"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Profile"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_remote_api_remotes__name__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Profile"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Profile"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  remove_remote_api_remotes__name__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  connect_remote_api_remotes__name__connect_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ConnectRequest"] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  disconnect_remote_api_remotes__name__disconnect_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  remote_benchmarks_api_remotes__name__benchmarks_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  remote_nodes_api_remotes__name__nodes_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  bootstrap_plan_api_remotes__name__bootstrap_plan_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlanResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  bootstrap_install_api_remotes__name__bootstrap_install_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InstallRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StepResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  bootstrap_verify_api_remotes__name__bootstrap_verify_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DetectResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_experiments_api_experiments_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LibraryEntry"][];
        };
      };
    };
  };
  create_experiment_api_experiments_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConfigBody"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SavedEntry"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_experiment_api_experiments__entry_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        entry_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LibraryEntry"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_experiment_api_experiments__entry_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        entry_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConfigBody"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SavedEntry"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_experiment_api_experiments__entry_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        entry_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  duplicate_experiment_api_experiments__entry_id__duplicate_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        entry_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LibraryEntry"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  local_benchmarks_api_local_benchmarks_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  submit_job_api_jobs_submit_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SubmitRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SubmissionAccepted"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_submission_api_jobs_submissions__submission_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        submission_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SubmissionStatus"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_jobs_api_jobs_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobListItem"][];
        };
      };
    };
  };
  cancel_job_api_jobs__record_id__cancel_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        record_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CancelResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  job_logs_api_jobs__record_id__logs_get: {
    parameters: {
      query?: {
        experiment?: string | null;
      };
      header?: never;
      path: {
        record_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  job_experiments_api_jobs__record_id__experiments_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        record_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  use_case_report_api_jobs_report__config_name__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        config_name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UseCaseReport"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  fetch_results_api_jobs__record_id__results_fetch_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        record_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FetchAccepted"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_fetch_status_api_jobs__record_id__results_fetch__fetch_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        record_id: string;
        fetch_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FetchStatus"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_results_api_jobs__record_id__results_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        record_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResultsData"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_results_cache_size_api_jobs_results_cache_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CacheSize"];
        };
      };
    };
  };
  clear_results_cache_api_jobs_results_cache_delete: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
